# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    paginator.items_per_page: 25

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true  # Automatically registers your services as commands, event subscribers, etc.

    App\Command\:
        resource: '../src/Command/*'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # -------------------------------------------------------------
    # Model
    # -------------------------------------------------------------

    App\Model\TypiCode\TypiCodeApiFacade: ~

    App\Model\Comment\CommentFactory: ~
    App\Model\Comment\CommentDtoFactory: ~
    App\Model\Comment\CommentRepository: ~
    App\Model\Comment\CommentFacade: ~

    App\Model\Post\PostFactory: ~
    App\Model\Post\PostDtoFactory: ~
    App\Model\Post\PostRepository: ~
    App\Model\Post\PostFacade: ~

    App\Model\User\UserFactory: ~
    App\Model\User\UserDtoFactory: ~
    App\Model\User\UserRepository: ~
    App\Model\User\UserFacade: ~